### PR TITLE
Network driver - block --internal from being used

### LINKED ISSUE #99: Calico plugin should enforce that a --internal option can't be passed to `docker network create`
This command should fail:
`docker network create $RANDOM --internal -d calico --ipam-driver calico-ipam`

--internal has no meaning when using Calico and could interfere.

### PR DESCRIPTION
**Pull request by tomdee**
Fixes #99

### CODE REVIEW

File: driver/network_driver.go [hunk 1]
```diff
@@ -71,6 +71,14 @@ func (d NetworkDriver) CreateNetwork(request *network.CreateNetworkRequest) erro
 		}
 	}
 
+	// Calico driver does not allow you use the --internal flag
+	internal, ok := request.Options["com.docker.network.internal"].(bool)
```
Comment (robbrockbank) [inline driver/network_driver.go]: I wonder if we should have a catch-all for any unexpected options - or at the very least be logging any options that we don't recognize?

**Comment by robbrockbank** [comment]
One general comment, but LGTM.
