### PR TITLE
Reject ipam options from being passed in

### LINKED ISSUE #100: Calico plugin should enforce that --ipam-opts options can't be passed to `docker network create`
i.e. this should fail `docker network create $RANDOM --ipam-opt REJECT -d calico --ipam-driver calico-ipam`

We already block network driver options, but not ipam driver options.

### PR DESCRIPTION
**Pull request by tomdee**
Fixes #100

### CODE REVIEW

**Comment by robbrockbank** [comment]
One comment, but LGTM.

File: driver/ipam_driver.go [hunk 1]
```diff
@@ -61,6 +61,12 @@ func (i IpamDriver) RequestPool(request *ipam.RequestPoolRequest) (*ipam.Request
 		return nil, err
 	}
 
+	if len(request.Options) != 0 {
+		err := errors.New("Arbitrary options are not supported")
+		log.Println(err)
```
Comment (tomdee) [inline driver/ipam_driver.go]: Aha, good point. Fixed.
